pid_controller:
  ros__parameters:
    desired_distance: 1.2     # How far you want to stay from the wall
    lookahead: 1.0            # Lookahead distance for projection
    theta_deg: 45.0           # Angle between beams (degrees)
    Kd: 0.09
    Ki: 0.4
    Kp: 0.9

pure_pursuit:
  ros__parameters:
    Kdd: 3.0
    min_ld: 0.3
    max_ld: 1.2
    max_steering_angle: 1.0
    wheel_base: 0.325  # Add this if your node expects it and you want it configurable

ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true

    odom0: "ego_racecar/odom"
    odom0_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    base_link_frame: "ego_racecar/base_link"
    map_frame: "map"
    world_frame: "map"

    publish_tf: true
    publish_acceleration: false

mpc_trajectory_tracker:
  ros__parameters:
    N: 20
    wheelbase: 0.34
    State_Weight:     [5.0, 5.0, 0.5, 1.0]      # Strong position tracking, moderate heading, weak speed
    Control_Weight:   [0.5, 1.0]                 # Light penalty on speed, moderate penalty on steering
    Terminal_Weight:  [25.0, 25.0, 5.0, 1.0]      # Strong incentive to finish close to final waypoint

    v_min: 1.0
    v_max: 4.0
    delta_min: -0.5
    delta_max: 0.5
